version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: luregenix
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  auth_service:
    build: ./services/auth_service
    depends_on:
      - postgres

  honeytoken_service:
    build: ./services/honeytoken_service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  event_service:
    build: ./services/event_service
    depends_on:
      - postgres

  gateway:
    build: ./gateway
    depends_on:
      - auth_service
      - honeytoken_service
      - event_service
    ports:
      - "8000:8000"

  agent:
    build: ./agent
    depends_on:
      - gateway

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway