include /etc/nginx/luregenix/default.conf;
server {
    listen 443 ssl;
    charset utf-8;
    server_tokens off;
    client_max_body_size 1m;
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_tickets off;
    include /etc/nginx/luregenix/headers.conf;
    include /etc/nginx/luregenix/locations.conf;
}
