name: Deploy to VirtualBox

on:
  push:
    branches: [ dev, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
    
    - name: Disable host key checking (проще некуда)
      run: |
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null" > ~/.ssh/config
    
    - name: Deploy
      run: |
        # Важно: используем порт 2222
        ssh -p 2223 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "
          cd ~/LureGenix
          git pull origin ${{ github.ref_name }}
          docker-compose down
          docker-compose up -d --build
          echo '✅ Деплой готов!'
        "